import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import PermissionProvider from '@/components/permission';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Root Layout',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	console.log('Root Layout');

	return (
		<html lang="en">
			<body className={inter.className}>
				<PermissionProvider>{children}</PermissionProvider>
			</body>
		</html>
	);
}
